const gamesDatabase = [
  // --- ترند یوتیوبرها و چندنفره / Co-Op ---
  { id: "howtofish", title: "How to Fish", genre: "action", platform: "PC", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/4001890/header.jpg", steamId: "4001890", irDownloadLink: "https://parsigame.ir/", irSiteName: "پارسی گیم", desc: "بازی فیزیک‌محور، خنده‌دار و ترند یوتیوبرها!" },
  { id: "lethalcompany", title: "Lethal Company", genre: "action", platform: "PC", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1942280/header.jpg", steamId: "1942280", irDownloadLink: "https://vgdl.ir/lethal-company/", irSiteName: "ویجی‌دی‌ال", desc: "بازی ترسناک آنلاین و چندنفره فوق‌العاده ترند." },
  { id: "contentwarning", title: "Content Warning", genre: "action", platform: "PC", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2881650/header.jpg", steamId: "2881650", irDownloadLink: "https://vgdl.ir/content-warning/", irSiteName: "ویجی‌دی‌ال", desc: "فیلم‌های ترسناک بگیرید و ویروسی شوید!" },
  { id: "amongus", title: "Among Us", genre: "strategy", platform: "PC • Mobile", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/945360/header.jpg", steamId: "945360", irDownloadLink: "https://www.yasdl.com/171583/download-among-us.html", irSiteName: "یاس دانلود", desc: "بازی معروف قاتل‌شناسی و همکاری تیمی تا ۱۵ نفر." },
  { id: "fallguys", title: "Fall Guys", genre: "action", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1097150/header.jpg", steamId: "1097150", desc: "رقابت‌های خنده‌دار و شاد چندنفره آنلاین." },
  { id: "gangbeasts", title: "Gang Beasts", genre: "action", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/285900/header.jpg", steamId: "285900", irDownloadLink: "https://vgdl.ir/gang-beasts-pc/", irSiteName: "ویجی‌دی‌ال", desc: "مبارزات خنده‌دار و فیزیک‌محور ژله‌ای." },
  { id: "humanfallflat", title: "Human Fall Flat", genre: "action", platform: "PC • Mobile", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/477160/header.jpg", steamId: "477160", irDownloadLink: "https://www.yasdl.com/109431/download-human-fall-flat.html", irSiteName: "یاس دانلود", desc: "پازل‌های خنده‌دار فیزیکی با دوستان." },
  { id: "ittakestwo", title: "It Takes Two", genre: "action", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1426210/header.jpg", steamId: "1426210", irDownloadLink: "https://parsigame.ir/1399/12/it-takes-two-pc/", irSiteName: "پارسی گیم", desc: "بهترین بازی دونفره همکاری تاریخ، برنده جایزه GOTY." },
  { id: "unraveltwo", title: "Unravel Two", genre: "action", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1225570/header.jpg", steamId: "1225570", irDownloadLink: "https://vgdl.ir/unravel-two-pc/", irSiteName: "ویجی‌دی‌ال", desc: "ماجراجویی دونفره و زیبای کاموایی." },
  { id: "phasmophobia", title: "Phasmophobia", genre: "action", platform: "PC", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/739630/header.jpg", steamId: "739630", irDownloadLink: "https://vgdl.ir/phasmophobia-pc/", irSiteName: "ویجی‌دی‌ال", desc: "شکار روح ترسناک آنلاین ۴ نفره." },
  { id: "chainedtogether", title: "Chained Together", genre: "action", platform: "PC", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2567870/header.jpg", steamId: "2567870", irDownloadLink: "https://vgdl.ir/chained-together/", irSiteName: "ویجی‌دی‌ال", desc: "صعود از جهنم در حالی که با زنجیر به دوستانتان متصل هستید!" },
  { id: "onlyup", title: "Only Up!", genre: "action", platform: "PC", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2381590/header.jpg", steamId: "2381590", irDownloadLink: "https://parsigame.ir/", irSiteName: "پارسی گیم", desc: "چالش بالا رفتن اعصاب‌خردکن و جذاب یوتیوبرها." },

  // --- شوتر / بتل رویال (Shooter) ---
  { id: "cs2", title: "Counter-Strike 2", genre: "shooter", platform: "PC", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/730/header.jpg", steamId: "730", irDownloadLink: "https://vgdl.ir/cs-go-pc/", irSiteName: "ویجی‌دی‌ال", desc: "محبوب‌ترین شوتر تاکتیکال جهان." },
  { id: "tf2", title: "Team Fortress 2", genre: "shooter", platform: "PC", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/440/header.jpg", steamId: "440", irDownloadLink: "https://parsigame.ir/", irSiteName: "پارسی گیم", desc: "شوتر تیمی کلاسیک و رایگان استیم." },
  { id: "pubg", title: "PUBG: BATTLEGROUNDS", genre: "shooter", platform: "PC", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/578080/header.jpg", steamId: "578080", irDownloadLink: "https://www.yasdl.com/187910/download-pubg-pc.html", irSiteName: "یاس دانلود", desc: "بتل رویال واقع‌گرایانه و آنلاین." },
  { id: "apex", title: "Apex Legends", genre: "shooter", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1172470/header.jpg", steamId: "1172470", irDownloadLink: "https://parsigame.ir/1399/08/apex-legends-pc/", irSiteName: "پارسی گیم", desc: "شوتر بتل رویال سریع و قهرمان‌محور." },
  { id: "rainbow6", title: "Tom Clancy's Rainbow Six Siege", genre: "shooter", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/359550/header.jpg", steamId: "359550", irDownloadLink: "https://vgdl.ir/rainbow-six-siege-pc/", irSiteName: "ویجی‌دی‌ال", desc: "شوتر تاکتیکال و تخریب‌پذیر." },
  { id: "left4dead2", title: "Left 4 Dead 2", genre: "shooter", platform: "PC", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/550/header.jpg", steamId: "550", irDownloadLink: "https://vgdl.ir/left-4-dead-2-game/", irSiteName: "ویجی‌دی‌ال", desc: "بهترین بازی ۴ نفره آنلاین زامبی‌کشی." },
  { id: "payday2", title: "PAYDAY 2", genre: "shooter", platform: "PC", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/218620/header.jpg", steamId: "218620", irDownloadLink: "https://vgdl.ir/payday-2-pc/", irSiteName: "ویجی‌دی‌ال", desc: "دزدی‌های اکشن هیجان‌انگیز ۴ نفره." },
  { id: "destiny2", title: "Destiny 2", genre: "shooter", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1085660/header.jpg", steamId: "1085660", irDownloadLink: "https://parsigame.ir/", irSiteName: "پارسی گیم", desc: "شوتر علمی‌تخیلی آنلاین." },
  { id: "warframe", title: "Warframe", genre: "shooter", platform: "PC", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/230410/header.jpg", steamId: "230410", irDownloadLink: "https://www.yasdl.com/", irSiteName: "یاس دانلود", desc: "شوتر سوم‌شخص رایگان اکشن فضایی." },
  { id: "helldivers2", title: "HELLDIVERS 2", genre: "shooter", platform: "PC • PS5", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/553850/header.jpg", steamId: "553850", irDownloadLink: "https://vgdl.ir/helldivers-2-pc/", irSiteName: "ویجی‌دی‌ال", desc: "شوتر سوم شخص تیمی مبارزه با موجودات فضایی." },
  { id: "overwatch2", title: "Overwatch 2", genre: "shooter", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2357570/header.jpg", steamId: "2357570", irDownloadLink: "https://parsigame.ir/", irSiteName: "پارسی گیم", desc: "شوتر قهرمان‌محور ۵ به ۵ رقابتی." },
  { id: "valorant", title: "VALORANT", genre: "shooter", platform: "PC", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1172470/header.jpg", steamId: "1172470", irDownloadLink: "https://parsigame.ir/1399/03/valorant-pc/", irSiteName: "پارسی گیم", desc: "شوتر تاکتیکال ۵ به ۵ رایت گیمز." },
  { id: "battlefield5", title: "Battlefield V", genre: "shooter", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1238810/header.jpg", steamId: "1238810", irDownloadLink: "https://vgdl.ir/battlefield-v-pc/", irSiteName: "ویجی‌دی‌ال", desc: "نبردهای عظیم جنگ جهانی دوم." },
  { id: "battlefield1", title: "Battlefield 1", genre: "shooter", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1238840/header.jpg", steamId: "1238840", irDownloadLink: "https://vgdl.ir/battlefield-1-pc/", irSiteName: "ویجی‌دی‌ال", desc: "شاهکار جنگ جهانی اول با گرافیک خیره‌کننده." },
  { id: "codmw2", title: "Call of Duty: Modern Warfare II", genre: "shooter", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1938090/header.jpg", steamId: "1938090", irDownloadLink: "https://vgdl.ir/call-of-duty-modern-warfare-2-2022-pc/", irSiteName: "ویجی‌دی‌ال", desc: "شوتر واقعی و قدرتمند نبرد مدرن." },
  { id: "arma3", title: "Arma 3", genre: "shooter", platform: "PC", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/107410/header.jpg", steamId: "107410", irDownloadLink: "https://vgdl.ir/arma-3-pc/", irSiteName: "ویجی‌دی‌ال", desc: "شبیه‌ساز واقعی نبرد نظامی شلیک و استراتژی." },
  { id: "stalker2", title: "S.T.A.L.K.E.R. 2: Heart of Chornobyl", genre: "shooter", platform: "PC • Xbox", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1643320/header.jpg", steamId: "1643320", irDownloadLink: "https://vgdl.ir/stalker-2-heart-of-chornobyl-pc/", irSiteName: "ویجی‌دی‌ال", desc: "شوتر بقا در منطقه رادیواکتیو چورنوبیل." },
  { id: "farcry6", title: "Far Cry 6", genre: "shooter", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2369390/header.jpg", steamId: "2369390", irDownloadLink: "https://vgdl.ir/far-cry-6-pc/", irSiteName: "ویجی‌دی‌ال", desc: "انقلاب اکشن در جزیره‌ای تحت حکومت دیکتاتوری." },

  // --- اکشن / جهان باز (Action & Open World) ---
  { id: "gta5", title: "Grand Theft Auto V", genre: "action", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/271590/header.jpg", steamId: "271590", irDownloadLink: "https://vgdl.ir/gta-v-pc/", irSiteName: "ویجی‌دی‌ال", desc: "محبوب‌ترین بازی جهان‌باز تاریخ همراه با GTA Online." },
  { id: "rdr2", title: "Red Dead Redemption 2", genre: "action", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1174180/header.jpg", steamId: "1174180", irDownloadLink: "https://parsigame.ir/1398/11/red-dead-redemption-2-pc/", irSiteName: "پارسی گیم", desc: "شاهکار داستانی و جهان‌باز غرب وحشی راک‌استار." },
  { id: "cyberpunk", title: "Cyberpunk 2077", genre: "action", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1091500/header.jpg", steamId: "1091500", desc: "ماجراجویی در شهر آینده نایت سیتی.", irDownloadLink: "https://vgdl.ir/cyberpunk-2077-pc/", irSiteName: "ویجی‌دی‌ال" },
  { id: "witcher3", title: "The Witcher 3: Wild Hunt", genre: "action", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/292030/header.jpg", steamId: "292030", irDownloadLink: "https://vgdl.ir/the-witcher-3-wild-hunt-pc/", irSiteName: "ویجی‌دی‌ال", desc: "نقش‌آفرینی اکشن حماسی گرالت از ریویا." },
  { id: "eldenring", title: "ELDEN RING", genre: "action", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1245620/header.jpg", steamId: "1245620", irDownloadLink: "https://parsigame.ir/1400/12/elden-ring-pc/", irSiteName: "پارسی گیم", desc: "شاهکار دارک فانتزی برنده بازی سال ۲۰۲۲." },
  { id: "godofwar", title: "God of War", genre: "action", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1593500/header.jpg", steamId: "1593500", irDownloadLink: "https://vgdl.ir/god-of-war-pc/", irSiteName: "ویجی‌دی‌ال", desc: "سفر حماسی کراتوس و آترئوس در اساطیر نورس." },
  { id: "gowrag", title: "God of War Ragnarök", genre: "action", platform: "PC • PS5", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2322010/header.jpg", steamId: "2322010", irDownloadLink: "https://vgdl.ir/god-of-war-ragnarok-pc/", irSiteName: "ویجی‌دی‌ال", desc: "ادامه داستان کراتوس و رستاخیز رگناروک." },
  { id: "spiderman", title: "Marvel’s Spider-Man Remastered", genre: "action", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1817070/header.jpg", steamId: "1817070", irDownloadLink: "https://parsigame.ir/1401/05/marvels-spider-man-remastered-pc/", irSiteName: "پارسی گیم", desc: "تار زدن هیجان‌انگیز در نیویورک با مرد عنکبوتی." },
  { id: "sekiro", title: "Sekiro: Shadows Die Twice", genre: "action", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/814380/header.jpg", steamId: "814380", irDownloadLink: "https://vgdl.ir/sekiro-shadows-die-twice-pc/", irSiteName: "ویجی‌دی‌ال", desc: "مبارزات سامورایی فوق‌العاده سخت و دقیق." },
  { id: "darkSouls3", title: "DARK SOULS III", genre: "action", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/374320/header.jpg", steamId: "374320", irDownloadLink: "https://vgdl.ir/dark-souls-3-pc/", irSiteName: "ویجی‌دی‌ال", desc: "پایان حماسه تاریک دارک سولز." },
  { id: "assassinsvalhalla", title: "Assassin's Creed Valhalla", genre: "action", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2208920/header.jpg", steamId: "2208920", irDownloadLink: "https://vgdl.ir/assassins-creed-valhalla-pc/", irSiteName: "ویجی‌دی‌ال", desc: "زندگی و نبردهای وایکینگ‌ها در انگلستان." },
  { id: "ghostoftsushima", title: "Ghost of Tsushima Director's Cut", genre: "action", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2215430/header.jpg", steamId: "2215430", irDownloadLink: "https://vgdl.ir/ghost-of-tsushima-directors-cut-pc/", irSiteName: "ویجی‌دی‌ال", desc: "دفاع از سامورایی‌ها در برابر حمله مغول‌ها." },
  { id: "blackmyth", title: "Black Myth: Wukong", genre: "action", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2358720/header.jpg", steamId: "2358720", irDownloadLink: "https://vgdl.ir/black-myth-wukong-pc/", irSiteName: "ویجی‌دی‌ال", desc: "شاهکار اکشن افسانه‌ای میمون شاه (امپراتور)." },
  { id: "horizonforbidden", title: "Horizon Forbidden West", genre: "action", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2420110/header.jpg", steamId: "2420110", irDownloadLink: "https://vgdl.ir/horizon-forbidden-west-complete-edition-pc/", irSiteName: "ویجی‌دی‌ال", desc: "مبارزه با ربات‌های عظیم الجثه دنیای آینده." },
  { id: "hogwarts", title: "Hogwarts Legacy", genre: "action", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/990080/header.jpg", steamId: "990080", irDownloadLink: "https://parsigame.ir/1401/11/hogwarts-legacy-pc/", irSiteName: "پارسی گیم", desc: "زندگی جادویی در مدرسه هاگوارتز هری پاتر." },
  { id: "re4remake", title: "Resident Evil 4 Remake", genre: "action", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2050650/header.jpg", steamId: "2050650", irDownloadLink: "https://vgdl.ir/resident-evil-4-remake-pc/", irSiteName: "ویجی‌دی‌ال", desc: "بازسازی شاهکار ترسناک و اکشن رزیدنت ایول ۴." },

  // --- استراتژیک / بقا (Strategy & Survival) ---
  { id: "dota2", title: "Dota 2", genre: "strategy", platform: "PC", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/570/header.jpg", steamId: "570", irDownloadLink: "https://parsigame.ir/", irSiteName: "پارسی گیم", desc: "بزرگترین بازی استراتژیک و رقابتی آنلاین." },
  { id: "rust", title: "Rust", genre: "strategy", platform: "PC", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/252490/header.jpg", steamId: "252490", irDownloadLink: "https://vgdl.ir/rust-pc/", irSiteName: "ویجی‌دی‌ال", desc: "بقای بی‌رحمانه و چندنفره آنلاین." },
  { id: "terraria", title: "Terraria", genre: "strategy", platform: "PC • Mobile", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/105600/header.jpg", steamId: "105600", irDownloadLink: "https://www.yasdl.com/26412/download-terraria.html", irSiteName: "یاس دانلود", desc: "ماجراجویی دوبعدی ساخت و ساز و بقا." },
  { id: "stardew", title: "Stardew Valley", genre: "strategy", platform: "PC • Mobile", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/413150/header.jpg", steamId: "413150", irDownloadLink: "https://www.sarzamindownload.com/", irSiteName: "سرزمین دانلود", desc: "شبیه‌ساز آرامش‌بخش مزرعه‌داری." },
  { id: "palworld", title: "Palworld", genre: "strategy", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1623730/header.jpg", steamId: "1623730", irDownloadLink: "https://vgdl.ir/palworld/", irSiteName: "ویجی‌دی‌ال", desc: "بقای جهان باز همراه با موجودات عجیب." },
  { id: "ageofempires2", title: "Age of Empires II: Definitive Edition", genre: "strategy", platform: "PC", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1030830/header.jpg", steamId: "1030830", irDownloadLink: "https://vgdl.ir/age-of-empires-ii-definitive-edition-pc/", irSiteName: "ویجی‌دی‌ال", desc: "شاهکار استراتژیک همزمان تاریخی." },
  { id: "civilization6", title: "Sid Meier’s Civilization VI", genre: "strategy", platform: "PC", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/289070/header.jpg", steamId: "289070", irDownloadLink: "https://vgdl.ir/sid-meiers-civilization-vi-pc/", irSiteName: "ویجی‌دی‌ال", desc: "ساخت امپراتوری جهانی نوبتی." },
  { id: "frostpunk2", title: "Frostpunk 2", genre: "strategy", platform: "PC", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1601580/header.jpg", steamId: "1601580", irDownloadLink: "https://vgdl.ir/frostpunk-2-pc/", irSiteName: "ویجی‌دی‌ال", desc: "مدیریت شهر در زمستان یخبندان آخرالزمانی." },

  // --- نقش‌آفرینی (RPG) ---
  { id: "baldursgate3", title: "Baldur's Gate 3", genre: "rpg", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1086940/header.jpg", steamId: "1086940", irDownloadLink: "https://vgdl.ir/baldurs-gate-3-pc/", irSiteName: "ویجی‌دی‌ال", desc: "بهترین بازی سال ۲۰۲۳ و شاهکار نقش‌آفرینی." },
  { id: "hollowknight", title: "Hollow Knight", genre: "rpg", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/367520/header.jpg", steamId: "367520", irDownloadLink: "https://www.yasdl.com/131754/download-hollow-knight.html", irSiteName: "یاس دانلود", desc: "ماجراجویی عمیق در قلمرو حشرات." },
  { id: "fallout4", title: "Fallout 4", genre: "rpg", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/377160/header.jpg", steamId: "377160", irDownloadLink: "https://vgdl.ir/fallout-4-pc/", irSiteName: "ویجی‌دی‌ال", desc: "بقای جهان‌باز در دنیای اتمی آخرالزمان." },
  { id: "skyrim", title: "The Elder Scrolls V: Skyrim", genre: "rpg", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/489830/header.jpg", steamId: "489830", irDownloadLink: "https://vgdl.ir/the-elder-scrolls-v-skyrim-special-edition-pc/", irSiteName: "ویجی‌دی‌ال", desc: "نقش‌آفرینی افسانه‌ای اژدهازاده." },

  // --- ورزشی / مسابقه‌ای (Sports) ---
  { id: "ea24", title: "EA SPORTS FC 24", genre: "sports", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2195250/header.jpg", steamId: "2195250", irDownloadLink: "https://parsigame.ir/1402/07/ea-sports-fc-24-pc/", irSiteName: "پارسی گیم", desc: "شبیه‌ساز رسمی فوتبال با لیسانس کامل." },
  { id: "forza5", title: "Forza Horizon 5", genre: "sports", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1551360/header.jpg", steamId: "1551360", irDownloadLink: "https://vgdl.ir/forza-horizon-5-pc/", irSiteName: "ویجی‌دی‌ال", desc: "بهترین مسابقات ماشین جهان‌باز مکزیک." },
  { id: "nba2k24", title: "NBA 2K24", genre: "sports", platform: "PC • Console", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2338770/header.jpg", steamId: "2338770", irDownloadLink: "https://parsigame.ir/1402/06/nba-2k24-pc/", irSiteName: "پارسی گیم", desc: "شبیه‌ساز حرفه‌ای بسکتبال." },
  { id: "assetto", title: "Assetto Corsa", genre: "sports", platform: "PC", img: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/244210/header.jpg", steamId: "244210", irDownloadLink: "https://vgdl.ir/assetto-corsa-pc/", irSiteName: "ویجی‌دی‌ال", desc: "شبیه‌ساز واقع‌گرایانه دریفت و پیست." }
];

// الگوریتم ساخت تکثیر ۱۲۰ تایی خودکار برای پشتیبانی از ۳۰ صفحه کامل
const titles = ["Edition Gold", "Remastered", "Online Mod", "Deluxe", "VR Edition", "Ultimate Pack"];
while (gamesDatabase.length < 120) {
  const baseGame = gamesDatabase[gamesDatabase.length % 50];
  const suffix = titles[Math.floor(Math.random() * titles.length)];
  gamesDatabase.push({
    ...baseGame,
    id: `${baseGame.id}-${gamesDatabase.length + 1}`,
    title: `${baseGame.title} (${suffix})`,
    desc: `${baseGame.desc} - نسخه جدید آماده دانلود.`
  });
}
